name: My First CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display message
        run: echo "Hello! My CI pipeline is working."

      - name: List files
        run: ls -la
